# For local testing, run:
# bundle exec jekyll serve --config _config.yml,_config-dev.yml
url: https://sylvainmetayer.fr

sass:
    sass_dir: _sass
    style: expanded # possible values: nested expanded compact compressed
