# For local testing, run:
# bundle exec jekyll serve --config _config.yml,_config-dev.yml
url: https://dev.sylvainmetayer.fr

isso:
    url: https://comments.sylvainmetayer.fr/dev/
    script: https://comments.sylvainmetayer.fr/dev/js/embed.min.js

show_drafts: true
profile: true

assets:
  source_maps: true # false on JEKYLL_ENV=production
  destination: "/assets"
  compression: false # true on JEKYLL_ENV=production
  gzip: false
  defaults:
      js: { integrity: false } # true on JEKYLL_ENV=production
      css: { integrity: false } # true on JEKYLL_ENV=production
      img: { integrity: false } # true on JEKYLL_ENV=production
  caching:
      path: ".jekyll-cache/assets"
      type: file # Possible values: memory, file
      enabled: true
  sources:
      - _assets/css
      - _assets/fonts
      - _assets/images
      - _assets/images/favicon
      - _assets/images/projets
      - _assets/videos
      - _assets/js
      - _assets/_sass
      - _assets/_sass/base
      - _assets/_sass/components
      - _assets/_sass/pages
